services:
    auth:
        image: v2
        path: k8s/auth/deployment.yaml
        replicas: 3
    order:
        image: order-service:v1
        path: k8s/order/deployment.yaml
        replicas: 2
