services:
    auth:
        image: auth-service:v1
        path: k8s/auth/deployment.yaml
        replicas: 2
    order:
        image: order-service:v1
        path: k8s/order/deployment.yaml
        replicas: 2
